# Site settings
title: My Portfolio
description: Some Of The Work I have Done
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ed Ssemuwemba
user_description: These are some of the tools I have used to accomplish my tasks
user_title: Software Developer
email: esseme@gmail.com
twitter_username: lorem_ipsum
github_username:  Esseme
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
