# Site settings
title: My Portfolio
description: Some Of The Work I have Done
base_url: ""
url: "https://edssemuwemba.com"

# User settings
username: Ed SSemuwemba
user_description: These are some of the tools that I use to accomplish my tasks.
user_title: Software Developer
email: esseme@gmail.com
twitter_username:
github_username:  Esseme
gplus_username:

# Google-analytics
google-analytics: G-CHHGQWQ0HH
exclude: ['package.json', 'src' , 'node_modules']
