# Site settings
title: My Portfolio
description: Some Of The Work I have Done
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ed SSemuwemba
user_description: These are some of the tools I have used to accomplish my tasks
user_title: Software Developer
email: esseme@gmail.com
twitter_username:
github_username:  Esseme
gplus_username:

# Google-analytics
google-analytics: G-CHHGQWQ0HH
exclude: ['package.json', 'src' , 'node_modules']
